### ISSUE TITLE
Can I use some kind of default routing?

### ISSUE THREAD

**Issue by InvisibleProgrammer** [InvisibleProgrammer/todo-clone#1]
That format looks terrible. Is it mandatory to set it at every page OR it is a configuration error OR it is only necessary if there is no controller class available just the single HTML?

```
@Configuration
public class MvcConfig implements WebMvcConfigurer {

    public void addViewControllers(ViewControllerRegistry registry) {
        registry.addViewController("/home").setViewName("home");
        registry.addViewController("/").setViewName("home");
        registry.addViewController("/hello").setViewName("hello");
        registry.addViewController("/login").setViewName("login");
    }
}
```

**Comment by zlaval** [comment]
Általában van hozzá üzleti igény és nem static viewkból áll az alkalmazás,  akkor controllert írsz rá, de amúgy így lehet automatikus controllert hozzárendelni.

Készőbb ha nem server side rendering lesz, ami mostanában nem szokás már, akkor ez a rész kiesik.
